### ISSUE TITLE
一影视1.4.2版TCL智能电视闪退

### ISSUE THREAD

**Issue by GaviTate** [tv-player/apks#12]
如题。电视系统的版本应该是V8-XXXX

**Comment by delury** [comment]
应该是不支持安卓5.0以下的系统。

**Comment by tv-player** [comment]
新版本已优化， 测试安卓5可以正常使用

**Comment by GaviTate** [comment]
> 新版本已优化， 测试安卓5可以正常使用
@tv-player 
1.5版实测可用了，播放流畅。👍👍👍
还有两个问题：
1、搜索或者换源，响应卡顿明显
2、集数上限只到1000。柯南等超过1000集的，后面列不出来

**Comment by tv-player** [comment]
1.5.1版本 已优化搜索卡顿问题
集数上限只到1000 是源的问题，可以切换源看看
