### ISSUE TITLE
你好  少儿的内容能补充下吗

### ISSUE THREAD

**Issue by duwei-coder** [tv-player/apks#25]
我的孩子特别喜欢你的软件  但是每次想搜索的时候不管是远程搜索还是首字母搜索一点反应都没有  不知道我哪儿操作没对.还有希望大佬能抽空将少儿益智类的视频补齐一下,感激不尽.白嫖你的软件还提这么多要求我也是非常抱歉  如果麻烦就算了

**Comment by tv-player** [comment]
升级2.0版本，资源全新优化了
