### ISSUE TITLE
一影视更新后，所有分区无法筛选，无法切换数据源和线路

### ISSUE THREAD

**Issue by sunguanghui** [tv-player/apks#3]
一影视更新后，所有分区无法筛选，设置中无法切换数据源和线路。

![Screenshot_2022-09-14-09-08-06-44_88987c23c9a2b586bca1863fdfc9e918](https://user-images.githubusercontent.com/14724891/190036156-19fbdc50-1ec0-4af3-9183-071c04820420.jpg)
![Screenshot_2022-09-14-09-07-52-40_88987c23c9a2b586bca1863fdfc9e918](https://user-images.githubusercontent.com/14724891/190036166-cd28ff92-2acd-408a-b734-eed059c28f36.jpg)

**Comment by tv-player** [comment]
一影视 爬虫已经升级， 脱离TVBox， 不会再有线路和数据源的设置。后续站点都单独维护

筛选数据正在维护，会尽快上线。

@sunguanghui
