### ISSUE TITLE
华为 P30 pro 升级出错

### ISSUE THREAD

**Issue by hu279318344** [tv-player/apks#30]
![99b98b8199b42e1dc044631f15a4482](https://github.com/tv-player/apks/assets/18319776/902fdde3-5257-4e90-a2bc-d0b46d56a465)
![d9e3ae144856c327b7e171090cc33ef](https://github.com/tv-player/apks/assets/18319776/21538a4d-fdc5-46bc-a095-fe960dcdd6ba)

**Comment by Jeffrey-jiacj** [comment]
![Screenshot_20230621_105951_com.android.packageinstaller.jpg](https://github.com/tv-player/apks/assets/63338454/2d8d0756-ee77-4827-baa1-b8c80c3050ab)

荣耀20pro更新一样报错，是不是鸿蒙系统不支持在线更新App？但是最新的安装包又没有下载链接

**Comment by tv-player** [comment]
[下载](https://ghproxy.com/https://raw.githubusercontent.com/tv-player/js-source/share/2.0.3.apk)

之前版本能正常更新吗

**Comment by Jeffrey-jiacj** [comment]
> [下载](https://ghproxy.com/https://raw.githubusercontent.com/tv-player/js-source/share/2.0.3.apk)
> 
> 之前版本能正常更新吗

使用这个下载链接在手机上可以正常安装。
![Screenshot_20230621_134902_com.okey.tvbox.box.jpg](https://github.com/tv-player/apks/assets/63338454/dae4eda7-4852-45a4-9e43-43b1ec943367)

**Comment by hu279318344** [comment]
> > [下载](https://ghproxy.com/https://raw.githubusercontent.com/tv-player/js-source/share/2.0.3.apk)
> > 之前版本本能正常更新吗
> 
> 使用这个下载链接在手机上可以正常安装。 ![Screenshot_20230621_134902_com.okey.tvbox.box.jpg](https://user-images.githubusercontent.com/63338454/247445196-dae4eda7-4852-45a4-9e43-43b1ec943367.jpg)
