### ISSUE TITLE
请问还有在维护吗？今天开始配置资源错误了。

### ISSUE THREAD

**Issue by Sanvnei1** [tv-player/apks#34]
也好久没更新了。

**Comment by Sanvnei1** [comment]
README.md 也删除了...

**Comment by tv-player** [comment]
还在维护， 错误提示什么

**Comment by Sanvnei1** [comment]
> 还在维护， 错误提示什么
![QQ图片20231021001951](https://github.com/tv-player/apks/assets/132321646/77a41b95-42ff-443d-94b8-14ffee93a5f7)

小米电视提示，配置错误。

**Comment by tv-player** [comment]
卸载重装试试

**Comment by Sanvnei1** [comment]
> 卸载重装试试

今天可以正常登录了，谢谢！
