### ISSUE TITLE
大佬最新版2.0.8在哪里下载

### ISSUE THREAD

**Issue by king4107** [tv-player/apks#35]
软件自动升级没反应

**Comment by tv-player** [comment]
之前地址被禁了，已更新

[手动下载](https://gh-proxy.com/https://raw.githubusercontent.com/tv-player/js-source/share/2.0.8.apk)

**Comment by king4107** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by king4107** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
